load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_proto_grpc",
    urls = ["https://github.com/rules-proto-grpc/rules_proto_grpc/archive/1.0.2.tar.gz"],
    sha256 = "5f0f2fc0199810c65a2de148a52ba0aff14d631d4e8202f41aff6a9d590a471b",
    strip_prefix = "rules_proto_grpc-1.0.2",
)

http_archive(
    name = "googleapi",
    urls = ["https://github.com/googleapis/googleapis/archive/common-protos-1_3_1.zip"],
    sha256 = "3ff2365822fb573cb1779ada5c2ac7899269cacd0836aef95ffe9d95779031f2",
    strip_prefix = "googleapis-common-protos-1_3_1",
    build_file = "@//:googleapi.BUILD",
)

load("@rules_proto_grpc//:repositories.bzl", "rules_proto_grpc_toolchains", "rules_proto_grpc_repos")
rules_proto_grpc_toolchains()
rules_proto_grpc_repos()

#load("@rules_proto_grpc//cpp:repositories.bzl", "cpp_repos")

#cpp_repos()

## the followings are for both cpp_proto_library and cpp_proto_compile
load("@rules_proto_grpc//cpp:repositories.bzl", rules_proto_grpc_cpp_repos="cpp_repos")

rules_proto_grpc_cpp_repos()


## the followings are for gRPC application
#load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    urls = ["https://github.com/grpc/grpc/archive/8cf19cfdd840731bb31665a757fd1074e58e8ce4.tar.gz"],
    strip_prefix = "grpc-8cf19cfdd840731bb31665a757fd1074e58e8ce4",
#    build_file = "@//app:BUILD",
)

## the followings are for cpp_grpc_compile, cpp_grpc_library AND for gRPC application
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")

grpc_deps()

